config/routes.rb
Admit::Application.routes.draw do
  devise_for :advisors

  resources :questions

  devise_for :applicants

  root to: "welcome#index"

end

app/models/advisor.rb
class Advisor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
         :username, :program, :country, :gmat_total, :gmat_quant, :gmat_verb,
         :undergrad, :gpa, :industry1, :industry2, :industry3

  validates :username, presence: true, uniqueness: true, format: { with: /^[a-zA-Z0-9_-]+$/, message: 'Must be formatted correctly' }
  validates :program, presence: true
 
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  validates :username, presence: true, uniqueness: true, format: { with: /^[a-zA-Z0-9_-]+$/, message: 'Must be formatted correctly' }

  has_many :questions


end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :applicant_id, :subject, :q_content

  belongs_to :applicant

  validates :q_content, presence: true, length: {minimum: 15}
  validates :subject, presence:true, length: {minimum: 15}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

before_filter :authenticate_applicant!

  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_applicant.questions.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/advisors/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
	<div class="navbar-header">
		<a class="navbar-brand" href="#">BuddySystem</a>
	</div>
	<div class="collapse navbar-collapse navbar-ex8-collapse">
		<ul class="nav navbar-nav">
		 <% if current_applicant.present? || current_advisor.present? %>	
			<li><%= link_to "All questions", questions_path %></li>
		 <% end %>		
		</ul>	
		
 	


		<ul class="nav navbar-nav pull-right">
			<% if current_applicant.present? %>
				<li><%= link_to current_applicant.email, edit_applicant_registration_path %></li>
				<li><%= link_to "Sign Out", destroy_applicant_session_path, :method => :delete %></li>
			<% elsif current_advisor.present?%>
				<li><%= link_to current_advisor.email, edit_advisor_registration_path %></li>
				<li><%= link_to "Sign Out", destroy_advisor_session_path, :method => :delete %></li>
			<% else %>
				<li><%= link_to "Sign up as applicant", new_applicant_registration_path %></li>
				<li><%= link_to "Log in as applicant", new_applicant_session_path %></li>
				<li><%= link_to "Sign up as an MBA advisor", new_advisor_registration_path %></li>
				<li><%= link_to "Log in as an MBA advisor", new_advisor_session_path %></li>
			<% end %>
		</ul>
	</div>
</nav>

	<div class="container">
			
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<%= yield %>

	</div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>

    <div class="form-group">
      <%= f.label :subject, class: "col-lg-3 control-label" %>
      <div class="col-lg-9">
        <%= f.text_field :subject, :autofocus => true, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label "Question", class: "col-lg-3 control-label" %>
      <div class="col-lg-9">
        <%= f.text_area :q_content, :autofocus => true, class: "form-control" %>
      </div>
    </div>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<%= link_to 'New Question', new_question_path, class: "btn btn-default" %>

  <% @questions.each do |question| %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><strong><%= question.applicant.username %>:</strong> <%= question.subject %></h3>
      </div>
      <div class="panel-body">
        <%= question.q_content %>
      </div>
      
      <div class="panel-footer">
        <%= link_to 'Show', question %>
        <%= link_to 'Edit', edit_question_path(question) %>
        <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
    

    
  <% end %>

<br />

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<h1>Showing this question</h1>



  
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><strong><%= @question.applicant.username %>:</strong> <%= @question.subject %></h3>
      </div>
      <div class="panel-body">
        <%= @question.q_content %>
      </div>
      
      <div class="panel-footer">
        <%= link_to 'Show', @question %>
        <%= link_to 'Edit', edit_question_path(@question) %>
        <%= link_to 'Destroy', @question, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>You worked hard for this moment</h1>
    <p>Most applications get rejected because the candidate didn't portray themselves well, not because they didn't deserve it.</p>
    <p><a class="btn btn-primary btn-lg">Error-check your application</a></p>
  </div>
</div>